version: "3.7"

services:
  web:
    image: nginx
    depends_on:
      - front
      - function
    ports:
      - 3003:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
  front:
    image: node:18-alpine
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c 'yarn --frozen-lockfile && yarn dev'
  function:
    image: node:18-alpine
    environment:
      NODE_OPTIONS: --openssl-legacy-provider
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c 'yarn --frozen-lockfile && yarn dev:functions'
